on:
  push:
    branches: [ master ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: "fc6fc1bc-af7e-44f9-9b74-c94adbebd130"
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: "1d3dff1d-ebee-4687-a9fb-9f7583d6a1a8"
      ARM_TENANT_ID: "761811ec-9396-4e4e-9ce9-bc2a6aa35b9f"
      working-directory: ./infrastructure

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ${{env.working-directory}}

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ${{env.working-directory}}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{env.working-directory}}
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{env.working-directory}}

  deploy:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'
          # extended: true

      - name: Build
        run: hugo

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
            azcliversion: 2.0.72
            inlineScript: |
                az storage blob upload-batch --account-name efgblogstore -d '$web' -s public/.

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
            azcliversion: 2.0.72
            inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "efg-cdn" --name "efg-blog-cdn" --resource-group "emilygorcenski-rg"
      
      - name: logout
        run: |
            az logout
